import moment from "moment";
import { Payload } from "@/types/Payload";
import { useQueryDuplicated } from "@/store/query-duplicated";
import { useTimeStore } from "@/store/time";

export function convertMsToHumanReadable(ms: number): string {
    if (ms < 1000) return `${ms.toFixed(2)} ms`;

    const seconds = (ms / 1000).toFixed(2);
    return `${seconds} s`;
}

export async function exportQueriesToSQL(queries: Payload[], requestId: string): Promise<void> {
    try {
        const filteredQueries = queries.filter((payload) => payload.request_id === requestId);

        if (filteredQueries.length === 0) {
            return;
        }

        const timeStore = useTimeStore();
        const duplicatesStore = useQueryDuplicated();
        const selectedRequest = timeStore.getSelectedRequest();

        const requestName = selectedRequest?.uri || "Tinker";
        const totalQueries = filteredQueries.length;
        const timestamp = moment().format("YYYY-MM-DD HH:mm:ss");
        const fileTimestamp = moment().format("YYYY-MM-DD_HH-mm-ss");

        let sqlContent = "";

        sqlContent += `-- ================================================\n`;
        sqlContent += `-- Generated by LaraDumps\n`;
        sqlContent += `-- Date: ${timestamp}\n`;
        sqlContent += `-- Request: ${requestName}\n`;
        sqlContent += `-- Total Queries: ${totalQueries}\n`;
        sqlContent += `-- ================================================\n\n`;

        filteredQueries.forEach((payload, index) => {
            const className = payload.ide_handle?.class_name || "Unknown";
            const lineNumber = payload.ide_handle?.line || 0;
            const sql = payload.queries?.query?.sql || "";
            const time = payload.queries?.query?.time || 0;
            const hasExplain = payload.queries?.explain && payload.queries?.explain_nodes;
            const isDuplicated = duplicatesStore.isDuplicated(payload.request_id, sql);

            sqlContent += `-- Query ${index + 1}/${totalQueries}\n`;
            sqlContent += `-- File: ${className}:${lineNumber}\n`;
            sqlContent += `-- Time: ${time}ms\n`;

            if (hasExplain) {
                sqlContent += `-- Explain: Available\n`;
            }

            if (isDuplicated) {
                sqlContent += `-- Duplicated: Yes\n`;
            }

            sqlContent += `${sql};\n\n`;
        });

        // Browser fallback
        if (typeof window.api === "undefined" || !window.api.invoke) {
            const blob = new Blob([sqlContent], { type: "text/plain" });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `queries-${fileTimestamp}.sql`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            return;
        }

        const result = await window.api.invoke("save-dialog", {
            title: "Export Queries",
            defaultPath: `queries-${fileTimestamp}.sql`,
            filters: [
                { name: "SQL Files", extensions: ["sql"] },
                { name: "All Files", extensions: ["*"] }
            ]
        });

        if (!result.canceled && result.filePath) {
            await window.api.invoke("write-file", {
                path: result.filePath,
                content: sqlContent
            });
        }
    } catch (error) {
        console.error("Error exporting queries:", error);
        throw error;
    }
}

